// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// Only load dotenv in non-production environments
if (process.env.NODE_ENV !== 'production') {
  await import("dotenv/config");
}

import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
